#!/bin/bash

# bash_aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# Git
alias g="git"
alias gs="git status"
alias gb="git branch"
alias gba="git branch -a"
alias gc="git commit -v"
alias gca="git commit -v -a"
alias gco="git checkout"
alias gd="git diff"
alias gdm="git diff master"
alias gh="github"
alias gl="git pull"
alias gp="git push"
# Commit pending changes and quote all args as commit message
function gg() {
	git commit -v -a -m "$*"
}
# Git archiving, filtered for modified files only
# Git archiving
function git_archive_modified_only()
{
	git archive --output="$1".zip HEAD $(git diff --name-only --diff-filter=M "$1" "$2" --stat)
}
# Git archiving
function git_archive()
{
	git archive --output="$1".zip HEAD $(git diff --name-only "$1" "$2" --stat)
}

# Reset previous commit, but keep all the associated changes.
alias goddammit="git reset --soft HEAD^"

# Open any files marked as “modified” in your default editor.
alias changed='open `git status --porcelain | sed -ne "s/^ M //p"`'

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Fancycat™
alias c="pygmentize -O style=solarized -f console256 -g"

# “What was that alias again?” Meta!
alias aliases="c ~/.dotfiles/bash/bash_aliases"

# IP addresses
alias ip='IP=`dig +short myip.opendns.com @resolver1.opendns.com`; growlnotify -s -a terminal -t "IP Address" -m "${IP}"'
alias lip='IP=`ipconfig getifaddr en0`; growlnotify -s -a terminal -t "Local IP" -m "${IP}"'

# Copy my public key to the pasteboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
alias flushdns="dscacheutil -flushcache"

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias showdotfiles="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidedotfiles="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"

# Processes
alias tu="top -o cpu" # cpu
alias tm="top -o vsize" # memory

# SSH Tunnels
function sshtun() {
	ssh -N $1 -L $2:127.0.0.1:$3 
}

# Common
#alias l="ls -laGH"

# Timestamp
alias ts="date +%s | pbcopy"

# Speed
#alias ..="cd ../" # up 1 directory

# Sites
alias sites="cd ~/Sites"

# Self-check
alias reload="source ~/.dotfiles/bash/bash_aliases" # reload aliases
alias ea="mate -w ~/.dotfiles/bash/bash_aliases && reload" # edit aliases in Textmate and reload
#alias ee="mate -w ~/bin/dotfiles/bash/evn" #edit env

# Create a dir and switch into it
function take {
	mkdir	 $1
	cd $1
}

# Get public facing IP
alias getip="curl -s http://checkip.dyndns.org | sed 's/[a-zA-Z/<> :]//g'"

# cd into whatever is the forefront Finder window.
cdf() {  # short for cdfinder
  cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"
}